services:
  app:
    entrypoint:
      - sleep
      - infinity
    image:  docker pull ghcr.io/mentasuave01/devcontainer-bun:1.1.21
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
